### ISSUE TITLE
CreateElement parameter not working 

### ISSUE THREAD

**Issue by butchiuk** [ErikSchierboom/knockout-pre-rendered#23]
Hi, I took your demo code for foreachInit and added createElement parameter: 

```html
<ul data-bind="foreachInit: {data: persons,createElement: addPerson }">
```
I also removed those 3 lines, as to populate the list dynamically with createElement.
```html 
viewModel.persons.push(new PersonViewModel());
viewModel.persons.push(new PersonViewModel());
viewModel.persons.push(new PersonViewModel());
```
It does populate it for the first element but breaks on the next one with error: 

```html 
TypeError: fieldAccessor is not a function
https://rawgit.com/ErikSchierboom/knockout-pre-rendered/master/dist/knockout-pre-rendered.js
Line 387
```

**Comment by ErikSchierboom** [comment]
This was actually a bug in my documentation. The `createElement` parameter used the `addPerson` method, which did not return a person but add it to the observable array. The documentation has been updated to fix this. This code does work:

```html
<ul data-bind="foreachInit: { data: persons, createElement: createPerson }">  
  <li data-template data-bind="text: name"></li>
  <li data-init data-bind="init, text: name">Michael Jordan</li>
  <li data-init data-bind="init, text: name">Larry Bird</li>
  <li data-init data-bind="init, text: name">Magic Johnson</li>
</ul>
```

combined with:

```js
function ForeachDynamicViewModel() {
  this.persons = ko.observableArray();

  this.createPerson = function() {
    return new PersonViewModel();
  }
}
```

I have also added an example of the `foreachInit` binding that uses `createElement`: http://output.jsbin.com/mapefa The readme also contains a link to this example.
