### ISSUE TITLE
Cannot use $index inside a foreachInit template

### ISSUE THREAD

**Issue by neRok-** [ErikSchierboom/knockout-pre-rendered#25]
As per title, I've tried all sorts and cannot access $index from within a template used for a foreachInit loop. I keep getting the error `ReferenceError: $index is not defined`. Perhaps I'm doing it wrong, but I'm wondering if it's some kind of error due to foreachInit.

**Comment by ErikSchierboom** [comment]
Weird, this should work as I create a child context for each item. Do you perhaps have a small repro?

**Comment by neRok-** [comment]
The following is based upon your demo code, and throws the error. It doesn't even try to initialise the original 'index' (which probably isn't needed anyway).

    <script src="https://cdnjs.cloudflare.com/ajax/libs/knockout/3.2.0/knockout-debug.js"></script>
    <script src="https://rawgit.com/ErikSchierboom/knockout-pre-rendered/master/dist/knockout-pre-rendered.js" type="text/javascript"></script>
    
    <script type="text/ko-template" id="personTemplate">
        <li>
            <span data-bind="text: $index"></span>
            <span data-bind="text: name"></span>
        </li>
    </script>
    
    <ul>
        
        <li data-init>
            <span>1</span>
            <span data-bind="init, text: name">Michael Jordan</span>
        </li>
        
    </ul>

    <form action="#">
        <input type="text" data-bind="value: newName" />
        <button class="form-control" data-bind="click: addPerson">Add person</button>
    </form>
    
    <pre style="white-space: pre-wrap;" data-bind="text: ko.toJSON(viewModel)"></pre>

    <script>
        function PersonViewModel(name) {
            var self = this;
            self.name = ko.observable(name);
        }

        function ViewModel() {
            var self = this;
            
            self.persons = ko.observableArray();

            self.addPerson = function() {
                var newPerson = new PersonViewModel(self.newName());
                self.persons.push(newPerson);
            };

            self.newName = ko.observable('Larry Bird');
            
        }

        var viewModel = new ViewModel();
        ko.applyBindings(viewModel);
    </script>
