### ISSUE TITLE
Problem with foreachInit template that contains table rows

### ISSUE THREAD

**Issue by neRok-** [ErikSchierboom/knockout-pre-rendered#26]
The following produces the error `TypeError: template is null`

    <script type="text/ko-template" id="personTemplate">
        <tr><td data-bind="text: name"></td></tr>
    </script>
    
    <table>
        <tbody>
            
            <tr data-init><td data-bind="init, text: name">Michael Jordan</td></tr>
            <tr data-init><td data-bind="init, text: name">Larry Bird</td></tr>
            <tr data-init><td data-bind="init, text: name">Magic Johnson</td></tr>
            
        </tbody>
    </table>

    <pre style="white-space: pre-wrap;" data-bind="text: ko.toJSON(viewModel)"></pre>

    <script>
        function PersonViewModel(name) {
            var self = this;
            self.name = ko.observable(name);
        }

        function ViewModel() {
            var self = this;
            self.persons = ko.observableArray();            
        }

        var viewModel = new ViewModel();
        ko.applyBindings(viewModel);
    </script>
The following works though. Note that the only difference is moving the template to within the foreachInit container.

    <table>
        <tbody>
            
            <tr data-template><td data-bind="text: name"></td></tr>
            <tr data-init><td data-bind="init, text: name">Michael Jordan</td></tr>
            <tr data-init><td data-bind="init, text: name">Larry Bird</td></tr>
            <tr data-init><td data-bind="init, text: name">Magic Johnson</td></tr>
            
        </tbody>
    </table>

    <pre style="white-space: pre-wrap;" data-bind="text: ko.toJSON(viewModel)"></pre>

    <script>
        function PersonViewModel(name) {
            var self = this;
            self.name = ko.observable(name);
        }

        function ViewModel() {
            var self = this;
            self.persons = ko.observableArray();            
        }

        var viewModel = new ViewModel();
        ko.applyBindings(viewModel);
    </script>
The problem appears to be specific to tables, as the following works

    <script type="text/ko-template" id="personTemplate">
        <li><span data-bind="text: name"></span></li>
    </script>
    
    <ul>
        
        <li data-init><span data-bind="init, text: name">Michael Jordan</span></li>
        <li data-init><span data-bind="init, text: name">Larry Bird</span></li>
        <li data-init><span data-bind="init, text: name">Magic Johnson</span></li>
        
    </ul>

    <pre style="white-space: pre-wrap;" data-bind="text: ko.toJSON(viewModel)"></pre>

    <script>
        function PersonViewModel(name) {
            var self = this;
            self.name = ko.observable(name);
        }

        function ViewModel() {
            var self = this;
            self.persons = ko.observableArray();            
        }

        var viewModel = new ViewModel();
        ko.applyBindings(viewModel);
    </script>

**Comment by ErikSchierboom** [comment]
Very odd, I'll look into it.

**Comment by ErikSchierboom** [comment]
As it turns out, this is actually the browser protecting from creating invalid HTML elements. What happens is that the plugin detects a `<script>` tag. It then creates a new `<div>` element that will get its `innerHTML` property set to the `innerHTML` of the `<script>` tag. However, as your `<script>` tag contains `<tr>` elements, which are not valid content for `<div>` elements, the `innerHtml` property is cleared. Hence the error message.

The fix is actually quite simple: just replace `<script>` with `<template>`:

```html
<template type="text/ko-template" id="personTemplate">
    <tr><td data-bind="text: name"></td></tr>
</template >

<table>
    <tbody>
        <!-- ko foreachInit: { data: persons, name: 'personTemplate', createElement: function() {return new PersonViewModel();} } -->
        <tr data-init><td data-bind="init, text: name">Michael Jordan</td></tr>
        <tr data-init><td data-bind="init, text: name">Larry Bird</td></tr>
        <tr data-init><td data-bind="init, text: name">Magic Johnson</td></tr>
        <!-- /ko -->
    </tbody>
</table>

<pre style="white-space: pre-wrap;" data-bind="text: ko.toJSON(viewModel)"></pre>

<script>
    function PersonViewModel(name) {
        var self = this;
        self.name = ko.observable(name);
    }

    function ViewModel() {
        var self = this;
        self.persons = ko.observableArray();            
    }

    var viewModel = new ViewModel();
    ko.applyBindings(viewModel);
</script>
```

**Comment by neRok-** [comment]
Yep, that works, thanks.
