### ISSUE TITLE
Support for attr binding, and/or custom bindings

### ISSUE THREAD

**Issue by neRok-** [ErikSchierboom/knockout-pre-rendered#27]
I am trying to bind the href attribute within a foreachInit loop, but I can't get it to work with the standard `attr {href:url}`, nor a custom binding. Reading some old issues, in particular #19, it seems that only specific bindings are currently supported. Is this true, and can any/all bindings be 'enabled'?

**Comment by ErikSchierboom** [comment]
It is true that at the moment it only works with specific bindings. For some bindings, being able to initialize the value might not really make sense. E.g. how would the `visible` binding work? Should it check the current element's visibility or what? 

Could you post an example of how you'd expect the `attr` binding to work with initialization? And if there are more bindings, please post an example of how you expect it to work. We can then discuss how it should be implemented here.

**Comment by neRok-** [comment]
Before I continue, just know that I'm new to Knockout, and have very little javascript experience, so I hope I'm getting all of the terminology and syntax correct.

The current value of whichever attribute should be used at the time that ko.applybindings is called. So yes, if the element had already been turned invisible when the bindings were applied, then the initial visible value should match. The same with any attr, eg the href value. So when you have `data-bind="init, attr {href:url}"`, at the time the bindings are applied, the url observable should be set to the elements href attribute.

So I would imagine `data-bind="init, attr {href:url}"` would do something like `url = ko.observable(element.getAttribute('href'))`.

**Comment by ErikSchierboom** [comment]
Okay, that makes sense. Could you post a list of what bindings you'd like to see supported and how they would work? The `attr` binding is fairly obvious, but the other ones might not be.

**Comment by neRok-** [comment]
It would make sense to support all of the bindings supplied with KO.

'visible', 'text', 'html' and 'attr' all seem straight forward.

I'm not sure what you could/should do for 'css' and 'style' though (I suppose this is why you asked originally). An example from the KO docs has `data-bind="css: { profitWarning: currentProfit() < 0 }"`. So say at init that the element has the profitWarning class, then would you have to set currentProfit to a value > 0? So yer, now I'm seeing the extent of the problem...

**Comment by ErikSchierboom** [comment]
I'll try to add the visible, html and attr bindings, text already works of course. I just noticed that the documentation implies that all bindinds are supported. This will also be corrected.

**Comment by ErikSchierboom** [comment]
I have just released version 0.6.0, which adds support for the following bindings:

- `attr`
- `html`
- `visible`
- `enable`
- `disable`

**Comment by pedrovagner** [comment]
This doesn't works `<a href="/some-url" data-bind="init, text: value, attr: {href: url}">some text</a>` but this works `<a href="/some-url" data-bind="init, text: value, init, attr: {href: url}">some text</a>`

Someone can confirm if `init` supports two bindings on the same element? If yes, would be nice to add this on README.md. Thanks.

**Comment by ErikSchierboom** [comment]
I'm afraid multiple init bindings are not supported, sorry.
