### ISSUE TITLE
$index not being updated when items removed from observableArray

### ISSUE THREAD

**Issue by neRok-** [ErikSchierboom/knockout-pre-rendered#28]
The following code will show the problem.

    <template type="text/ko-template" id="rowTemplate">
        <li>Index <span data-bind="text: $index"></span> : <span data-bind="text: word"></span></li>
    </template>
    
    <ul style="height:4em;">
        
            <li data-init>Index <span data-bind="text: $index"></span> : <span data-bind="init, text: word">Zero</span></li>
            <li data-init>Index <span data-bind="text: $index"></span> : <span data-bind="init, text: word">One</span></li>
            <li data-init>Index <span data-bind="text: $index"></span> : <span data-bind="init, text: word">Two</span></li>
        
    </ul>

    <p>Run through these buttons in order. A regular foreach loop will update all indexes correctly as items are removed, but foreachinit doesn't.</p>
    <ol>
        <li><button class="form-control" data-bind="click: addRow">Add a new row</button></li>
        <li><button class="form-control" data-bind="click: removeRow">Remove first row</button></li>
        <li><button class="form-control" data-bind="click: addRow">Add a new row</button></li>
        <li><button class="form-control" data-bind="click: removeRow">Remove first row</button></li>
        <li><button class="form-control" data-bind="click: addRow">Add a new row</button></li>
        <li><button class="form-control" data-bind="click: removeRow">Remove first row</button></li>
        <li><button class="form-control" data-bind="click: addRow">Add a new row</button></li>
    </ol>
    <p>Because knockout-pre-rendered isn't working correctly, all of the indexes will be '3'.</p>

    <script>
        
        function Row(word) {
            var self = this;
            self.word = ko.observable(word);
        };
            
        function ViewModel() {
            var self = this;
            
            self.rowArray = ko.observableArray();

            self.addRow = function() {
                self.rowArray.push(new Row(Date.now()));
            };

            self.removeRow = function() {
                self.rowArray.shift();
            };

        }

        var app = new ViewModel();
        ko.applyBindings(app);
    </script>

**Comment by ErikSchierboom** [comment]
I think I fixed this problem. You can find the code in the `index-delete` branch. Could you check to see if it is working for you?

**Comment by ErikSchierboom** [comment]
See also a new fiddle: http://output.jsbin.com/fahoci

**Comment by neRok-** [comment]
Yep, works for me.
