### ISSUE TITLE
Click event binding

### ISSUE THREAD

**Issue by bradrydzewski** [ErikSchierboom/knockout-pre-rendered#34]
Hey there, I'm using `data-bind="foreachInit: users"` to bind a pre-rendered list of users in a table, which is working very well. I'd like the ability to bind click events to the pre-rendered data, specifically, a button to delete from the list.

The markup looks something like this (some code omitted):

```html
<tr data-init>
	<td data-bind="init, text: login">octocat</td>
	<td data-bind="init, text: email">octocat@github.com</td>
	<td>
		<button data-bind="init, click: $parent.removeUser">delete</button>
	</td>
</tr>
```

And the view model:

```js
function UserViewModel() {
	var self = this;
	self.users = ko.observableArray();
	self.removeUser = function(user) {
		self.users.destroy(user);
	};
}

ko.applyBindings(new UserViewModel());
```

I noticed a list of supported binding in the readme, and the `click` event was not included. Is this something that could be included? Or is there a different approach you'd recommend? Thanks!

**Comment by ErikSchierboom** [comment]
The `click` event is not included as it cannot be initialized, but it should just work! Just remove the `init` part from the button: `<button data-bind="click: $parent.removeUser">delete</button>` That should work.

I have modified my sample application to show you how it works: http://output.jsbin.com/guwono
