### ISSUE TITLE
Dynamic model

### ISSUE THREAD

**Issue by f0def** [ErikSchierboom/knockout-pre-rendered#37]
Is there a way not described by the model? To initialize the properties of a model based on a template received.
Something like this for not existed properties:
```html
<input data-bind="init: {createIfNotExists: 'observable'}, value: dynamicProperty" type="text"/>
```
This will populate viewModel:
```js
function ViewModel(){}
ViewModel.prototype.dynamicProperty = ko.observable(); //or ko.observableArray(); what specified
```
Or may be some API that allow to specify what to do if property not found on model (with argument = `data-bind` object).

**Comment by ErikSchierboom** [comment]
I'm sorry, but there is no such thing. This library only works for existing models.

**Comment by f0def** [comment]
@ErikSchierboom thanks for fast reply, ok!
I will generate `<script>` at server
