### ISSUE TITLE
Animating adding/removing

### ISSUE THREAD

**Issue by Solanar** [ErikSchierboom/knockout-pre-rendered#38]
The knockout `foreach` binding has two paramters `beforeRemove` and `afterAdd` which allow you to animate adding/removing elements. Does knockout-pre-rendered support anything like this?

**Comment by ErikSchierboom** [comment]
@Solanar Not at the moment. I will consider adding it.

**Comment by Solanar** [comment]
Workaround:
```
<data-bind="foreachInit: { afterQueueFlush: animate }">
    <data-template id="id_template">

view_model = new ViewModel();

view_model.animate = function(elements) {
    for (var i = 0; i < elements.length; ++i) {
        if (elements[i].status == 'added') {
            var template = $("#id_template");
            template.removeAttr('id');
            template.hide();

            template.fadeIn();
        }
    }
}
```

**Comment by joelcuevas** [comment]
@Solanar, really nice workaround! Thank you! I was looking for the same thing.

@ErikSchierboom, `beforeQueueFlush` and `afterQueueFlush` are very useful events! You should consider mentioning them in the docs.

**Comment by ErikSchierboom** [comment]
@Solanar Are the `beforeQueueFlush` and `afterQueueFlush` enough for you to support your use-case? In other words, is there still a need for a `beforeRemove` or `afterAdd` method?
