### ISSUE TITLE
foreachInit: remove server side rendering

### ISSUE THREAD

**Issue by specialagentjosh** [ErikSchierboom/knockout-pre-rendered#39]
should the initial server side rendering within a foreachInit not be removed when the viewModel data binding kicks in? Otherwise you end up with both the server and client side rendering when your viewModel is populated which seems to defeat the purpose. Or am I missing something which is entirely possible? thx

**Comment by ErikSchierboom** [comment]
Actually, the idea of this library is that server-side and client-side rendering are mixed. If you want the initial server-side rendering to be removed, you can just use the regular Knockout `foreach` binding.

**Comment by specialagentjosh** [comment]
but if i use a regular foreach, KO will immediately re-render the DOM when the page first loads. My goal is to render server-side code on initial page load and "delay" KO bindings / rendering until the viewModel changes from the initial value. Your library accomplishes this, except it does not remove the initial server-side DOM rendering with foreachInit when the viewModel changes from the init value.

effectively trying to (1) afford SEO value and (2) reduce unnecessary processing until the viewModel changes from the init value.

Anywho ... nice job on this and thanks for the quick reply. going to take a slightly different approach

**Comment by ErikSchierboom** [comment]
@specialagentjosh Good luck!
