### ISSUE TITLE
foreachInit with computedObservable

### ISSUE THREAD

**Issue by JZubero** [ErikSchierboom/knockout-pre-rendered#46]
I was wondering if it is possible to use a computedObservable for the foreachInit binding? I have a list that needs some dynamic filtering which I would like to apply in the read method of the computedObservable through KO's dependency tracking mechanism. If this was intended to be handled in another way I am open for suggestions of course ;-)

**Comment by ErikSchierboom** [comment]
@JZubero sorry for the late reply, but I was away on holiday. In theory, if your computed observable has a setter available, it should work.

**Comment by JZubero** [comment]
@ErikSchierboom no problem, hope you had a nice holiday. Hm, I am not sure how the setter of the computed observable is intended to be used for that. I have created a fiddle with some comments, maybe you could have a quick look? https://jsfiddle.net/2yuovxyu/18/

**Comment by ErikSchierboom** [comment]
Well, the `write` part should store the data in the backing field, so something like this:

```javascript
write: function(value) { 
    this.persons(value);
}
````

However, that doesn't work when I tried it. I'll look at someday soon.

**Comment by ErikSchierboom** [comment]
I've just taken a look at this, but I did not manage to get it working unfortunately. Support for computed observables was missing and I just added (it's in version 0.9.0), but the filtering somehow messes up knockout. If you just use a plain observable array as a backing field, it works:

```javascript
this.persons = ko.observableArray();
  
  /**
   * When the test filter is active, only Michael and Magic should be delivered via Getter
   */
  this.filteredPersons = ko.pureComputed({
  	read: function() {
      return self.persons();
    },
    write: function(value) {
    	self.persons(value);
    },
    owner: this
  });
```

However, the filtering messes things up. I'm afraid I don't know why, sorry.

**Comment by JZubero** [comment]
Hm, thanks for checking anyway. If this becomes a blocker for me I will have a closer look at it.

**Comment by ErikSchierboom** [comment]
@JZubero Okay cool. I'll close it for now. If it does become a blocker, we can always re-open it.
