### ISSUE TITLE
Doesn't work with computed?

### ISSUE THREAD

**Issue by EmilianoBruni** [ErikSchierboom/knockout-pre-rendered#49]
I try to use your js with computed element. 

`<span data-bind="init, html: test">Hello</span>`

where test is

`this.test = ko.computed(function() { return 'IT WORKS' }, this);`

but I get this knockout error

> Error: Unable to process binding "init: function(){return undefined }" Message: Cannot write a value to a ko.computed unless you specify a 'write' option. If you wish to read the current value, don't pass any parameters.`

**Comment by ErikSchierboom** [comment]
Well, that is not a supported use case. You are trying to use a read-only computed value with the pre-rendered library, but this is not what the pre-rendered library is designed to do. The aim of the pre-rendered library is to fill Knockout model values with pre-rendered HTML. In your case, it tries to assign the `Hello` value from the HTML to the `test` observable. As that observable is read-only, it fails. To fix this, you should either make it a regular observable or a computed value that also support writing values.
