### ISSUE TITLE
foreachInit with multiple adjacent HTML nodes per array element.

### ISSUE THREAD

**Issue by revengineering** [ErikSchierboom/knockout-pre-rendered#50]
I have a situation where I'd like to use foreachInit in a table, but each element in the array needs to bind to two `<tr>` elements instead of one.

```
<table>
    <tbody data-bind="foreachInit: { data: rows, name: 'personTemplate', createElement: createRow }">
        <tr class="element-row-1">
            <td data-bind="init, text: FirstName">Joe</td>
            <td data-bind="init, text: LastName">Smith</td>
            <td data-bind="init, text: EmailAddress">jsmith@smith.com</td>
        </tr>
        <tr class="element-row-2">
            <td colspan="3" data-bind="init, text: Comments">Freeform comments... blah blah blah...</td>
        </tr>

        <tr class="element-row-1">
            <td data-bind="init, text: FirstName">Bob</td>
            <td data-bind="init, text: LastName">Edwards</td>
            <td data-bind="init, text: EmailAddress">redwards@edco.test.com</td>
        </tr>
        <tr class="element-row-2">
            <td colspan="3" data-bind="init, text: Comments">blah blah blah...</td>
        </tr>

        <tr class="element-row-1">
            <td data-bind="init, text: FirstName">Steve</td>
            <td data-bind="init, text: LastName">Jacobs</td>
            <td data-bind="init, text: EmailAddress">sjacobs@adsf.org</td>
        </tr>
        <tr class="element-row-2">
            <td colspan="3" data-bind="init, text: Comments">other comments</td>
        </tr>
    </tbody>
</table>

<script id="personTemplate" type="script/ko-template">
    <tr class="element-row-1">
        <td data-bind="text: FirstName"></td>
        <td data-bind="text: LastName"></td>
        <td data-bind="text: EmailAddress"></td>
    </tr>
    <tr class="element-row-2">
        <td colspan="3" data-bind="text: Comments"></td>
    </tr>
</template>
```
Obviously, the result of the code above is that my array of `rows` ends up with double the number of elements, since it's creating one element for each `<tr>` it finds.

Same problem would apply when using `data-init`, since there's no container grouping both `tr`s  together in the same `data-init`.

I could of course bind my array elements to a `tbody`, in which case I'd have one `tbody` per person, each containing the two rows. But that's not ideal here...

In plain knockout client-side rendering, I could do the following:
```
    <tbody data-bind="foreach: rows">
        <tr class="element-row-1">
            <td data-bind="text: FirstName"></td>
            <td data-bind="text: LastName"></td>
            <td data-bind="text: EmailAddress"></td>
        </tr>
        <tr class="element-row-2">
            <td colspan="3" data-bind="text: Comments"></td>
        </tr>
    </tbody>
```
How can I preserve the same output structure using knockout-pre-rendered `foreachInit`?

**Comment by revengineering** [comment]
**Suggested solution, syntax-wise:**  
Add a `nodesPerElement` option to `foreachInit` binding, telling it how many dom nodes there are per element in the array.
`data-bind="foreachInit: { data: rows, name='rowTemplate', createElement: newRow, nodesPerElement: 2 }`
This would prevent the actual content from ballooning out with container elements.

**Comment by revengineering** [comment]
Yeah, I started looking at it. I think it might be doable. I'm certainly willing to take a crack at it. If you have any better suggestion for the name of the option (nodesPerElement), let me know.

**Comment by ErikSchierboom** [comment]
Not really, I think the name is fine as is.

**Comment by revengineering** [comment]
Resolved!

**Comment by ErikSchierboom** [comment]
:tada:
